### ISSUE TITLE
[LE] Create template database

### ISSUE THREAD

**Issue by dangershony** [stratisproject/FederatedSidechains#100]
The class that will push tx templates to disk, should use the debreeze db.

Probably does not need to habdle deletetions are reorg should never happen.

**Comment by quantumagi** [comment]
Continuing work on this.

**Comment by quantumagi** [comment]
Chain B - Receive Store
-------------------------
- Deposit Transaction ID
- Deposit Block Height
- Deposit Target Address
- Deposit Amount
- Partial Transaction Hex
- Partial Transaction Hash
- Transaction Block Height
- Transaction Block Hash
- Signatures
- Status
  - "Deposit Received"
  - "Partial Transaction Created" (Depends on UTXO availability)
  - "Fully signed"
  - "Broadcasted"
  - "Seen in Block"
  - "Complete" (Reorg depth reached)
  - "Rejected"

Also node B needs to keep track of:
- the last chain B block (the "store tip") that information is included for in the above store.
- the last chain A block that that information is included for in the above store.

We can track that in a separate table on DBreeze (e.g. "Common").
