### ISSUE TITLE
Rework how the leader selects current/previous tx

### ISSUE THREAD

**Issue by dangershony** [stratisproject/FederatedSidechains#103]
This task is about how the leader processes its own transactions (in the current block that made it the leader) and before that any previous transactions that have not been processed.
cf. #75 

***In order to*** ensure that cross chain transfers are dealt with in their order of appearance on chain A
***As a*** federated member's B-node
***I want*** to validate the status of all previous transactions and process the ones that need to chronologically

> NOTE:  
    - processing things in chronological order is key to building transactions deterministically, since all members need to agree on which UTXOs are going to be picked up
    - the kind of processing required by different transactions is explained in issue #134

#### Acceptance Criteria 

- When a new leader is elected as a result of chain A progressing, every node from chain B needs to search its database for all transactions that are not yet in chain B's mempool, then process them.
- When a new message appears for block i+1, all nodes need to check that they received all information for blocks up to i, if it is not the case, they need to ask their node A for all missing information, and process them chronologically before

**Comment by quantumagi** [comment]
**Acceptance Criteria**
- When a new leader is elected as a result of chain A progressing, every node from chain B needs to search its database for all transactions that are not yet in chain B's mempool, then process them.
**Given that all the chain B nodes are keeping up with chain A anyway (the next point) it should be sufficient for the leader to then select the next transaction to broadcast by calling the stores' `GetTransferByStatusAsync(CrossChainTransferStatus.FullySigned` method.** 
- When a new message appears for block i+1, all nodes need to check that they received all information for blocks up to i, if it is not the case, they need to ask their node A for all missing information, and process them chronologically before
**Given that the store keeps track of the next chain A block it wants it should be sufficient for all chain B nodes to keep feeding the store with the blocks it wants via the  ` RecordLatestMatureDepositsAsync' method. If node B does not have the required information in memory it should request it form node A.**
