### ISSUE TITLE
Deterministic creation of target transactions

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/FederatedSidechains#108]
With the new design to handle cross chain transfers, we are going to need to create transactions that take funds out of the multisig and into targeted chain addresses in a deterministic way.
This will allow all federation members to come up with the exact same transaction without communication, and we are hoping that this will result in a more fault tolerant federation.

An basic idea for the design is explained here
https://github.com/stratisproject/FederatedSidechains/blob/master/Requirements/cross-chain-transfer.md#3-building-the-chain-b-transaction-deterministically

Please feel free to ask if any detail is missing there!

**Comment by bokobza** [comment]
Please refer to https://github.com/stratisproject/FederatedSidechains/blob/master/requirements/cross-chain-transfer.md#3-building-the-chain-b-transaction-deterministically
