### ISSUE TITLE
Define key functionalities for the federation dashboard

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/FederatedSidechains#115]
We need to come up with a bunch of functionalities that a sidechain dashboard needs to offer, and if it is in scope for this first prod release...

Each member/node could offer a few API endpoints to report 
- Status of other members/nodes (maybe push warnings on members unavailability)
- Query status of transfers by source or target address, by block number, for each transfer
  + transfer details
  + session leader table
  + amounts and target address
  + current transaction template state (pending maturity, initiated, signed by 1,2,3 members, in mempool, on chain, on chain and matured, rejected)
- Query tranfers by status for date range
- Current (and future for the next 5-10 blocks) transfer session leaders (for both chains)
- Current (and future for the next 5-10 blocks) block producer (for POA)
- Multisig addresses and balance (confirmed, pending)
- Trigger node resync (resync chains)
- Trigger session reset (resync cross chain transfers since block X), this is needed for recovery after an offline period anyway

**Comment by bokobza** [comment]
We could potentially use SignalR to push data to the dashboard.

**Comment by bokobza** [comment]
this is done for now.
