### ISSUE TITLE
Issue Smart Contract nuget package

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/FederatedSidechains#116]
Please please please :) We need to reference the SC networks in the Sidechain project!

**Comment by dangershony** [comment]
@codingupastorm @rowandh @bokobza @fassadlr 

I think we need to change the smart contract network to actually be the APEX network that we used in sidechains.

At the momnet I see stuff like `SmartContractPosTestnet`, for the rest of the code we actually test with a real network (Stratis, Bitcoin) perhaps we should do the same here, this can go in the `Stratis.Bitcoin.Networks` project.

**Comment by codingupastorm** [comment]
Hey guys. Very happy to help you with whatever you need.

Could you please tell us what you would like? It's hard for us to tell from this.

Move our Networks to the Networks folder? Change some params to be more like APEX?
