### ISSUE TITLE
Change federation wallet to native multisig

### ISSUE THREAD

**Issue by zeptin** [stratisproject/FederatedSidechains#124]
This may be required if the smart contracts functionality disallows P2SH on the sidechain network.

Alternatively, maybe the rule can be relaxed to allow P2SH for federation members only?

**Comment by zeptin** [comment]
https://github.com/stratisproject/StratisBitcoinFullNode/issues/1835

**Comment by codingupastorm** [comment]
Closing this as we amended the smart contract rule to allow P2SH, so it seems there's no immediate benefit to doing this anymore.
