### ISSUE TITLE
Block observer with MaxReorg + 1 delay

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/FederatedSidechains#128]
This block observer should raise an event whenever a new block has passed MaxReorg + 1 maturity. Eventually, when this event happens, a message will be sent to the other chain's node to describe potential deposits, or the absence of deposits.

***In order to*** build a message to send to chain B node
***As a*** federated member chain A node
***I want*** an event to be triggered when this a block matures

*NOTE: message structure is defined in issue XX*

#### Acceptance Criteria

- if a blocks matures, a new event is sent, that event needs to contain enough information to build a message that will be sent to this federation member counter node (the node watching chain B).

**Comment by bokobza** [comment]
Done in https://github.com/stratisproject/FederatedSidechains/commit/4ac552c104686966ae91d82cf0ebd4d65e1a2b14
