### ISSUE TITLE
Block matured message exchange sender

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/FederatedSidechains#129]
***In order to*** pass deposit (or absence of deposit) information from A-node to B-node
***As a*** federated member chain A node
***I want*** to react to block maturing events, by composing and sending a message to my B-node.

> NOTE: message structure is defined in issue #130 

#### Acceptance Criteria

- when a blocks matured event is observed, the content of the block relevant to cross chain deposits is extracted and put into a message.

**Comment by bokobza** [comment]
Done in https://github.com/stratisproject/FederatedSidechains/pull/151
