### ISSUE TITLE
Block matured message exchange receiver

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/FederatedSidechains#131]
***In order to*** receive deposit (or absence of deposit) information from A-node to B-node
***As a*** federated member chain B node
***I want*** receive messages sent from my A-node into my B-node.

> NOTE: message structure is defined in issue #130 

#### Acceptance Criteria

- when a message containing information about new matured blocks is sent from A Chain, it is received and digested by the B node

**Comment by bokobza** [comment]
Done in https://github.com/stratisproject/FederatedSidechains/pull/151
