### ISSUE TITLE
Leader ordering and change

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/FederatedSidechains#132]
Order fed members alphabetically by public key, and use that order + the block heights to select preferred leaders in a round robin fashion, when a new message arrives (triggered by new blocks tip height).

***In order to*** agree on who is the leader for the deposit of a given block
***As a*** federated member
***I want*** to agree with my other federation fellows on who is the leader for every block that may appear in the future

> this might be as simple as a "modulo" operation

#### Acceptance Criteria

- Leader is selected deterministically based on the public keys of the multisig, and the height of a given block
- Upon receiving a new message (Block Tip HashHieght Pair) from the block signaler, the new leader is selected automatically
- All federation members get the same number of opportunities to be leaders

**Comment by ferdeen** [comment]
For this task : 

1. Create a block tip hash height pair signaler

  When a new block tip is discovered.  
  Call the Target endpoint `SendBlockTip()`.

2. In the Federation Gateway receive the block tip and calculate the next federated member leader.

  Create a controller `SendBlockTip()`.
  In the method call `LeaderProvider.Update(BlockTip HashHieghtPair)` to compute the leader.
  To retrieve the leader call the get property `LeaderProdvider.CurrentLeader`

**Comment by bokobza** [comment]
Done in https://github.com/stratisproject/FederatedSidechains/pull/150
