### ISSUE TITLE
Reprocessing needs for each transfer status

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/FederatedSidechains#134]
***In order to*** allow a new leader to pick up and continue processing a transaction that was already started
***As a*** federated member's B node
***I want*** to be able to decide on what operations I need to perform to ensure the new leader has a chance to pick up that transfer

> NOTE:  
    - operations have to be performed on each transaction chronologically based (cf. issue #103)

#### Acceptance Criteria 

- When a partially signed transaction is received from another B node, but doesn't tie to the information received my own A node, it needs to be rejected.
- When a partially signed transaction is received from another B node, but I don't have the information to validate / sign it, I need to request my A node for that information (resync from at least the corresponding block on chain A)
- When a transaction is known but has not made it to the mempool, all nodes should rebroadcast the corresponding template with their signatures (cf. issue #103)
- When a transaction has been found on chain B, nothing needs to be done
- When a transaction was found on chain B, but then got involved in a reorg, the node B needs to resync, then the corresponding template transaction needs to be rebuilt using up to date UTXOs, and look on chain and in the mempool for its status
- When a transaction has matured on chain B, nothing needs to be done

**Comment by quantumagi** [comment]
Issue https://github.com/stratisproject/FederatedSidechains/issues/184 created for adding `Suspended` status to the store.

**Comment by quantumagi** [comment]
**Acceptance Criteria**

- When a partially signed transaction is received from another B node, but doesn't tie to the information received my own A node, it needs to be rejected.
**Each node receives both the deposit id and the partial transaction. If the partial transaction template does not match an EXISTING recorded transaction template for that deposit id then it will be rejected.**
- When a partially signed transaction is received from another B node, but I don't have the information to validate / sign it, I need to request my A node for that information (resync from at least the corresponding block on chain A) **The chain B node should ideally be requesting deposits for its currently recorded chain A tip regardless of circumstance. It should not advance its recorded chain A tip if there are still unresolved or non-funded transactions for the current tip.**
- When a transaction is known but has not made it to the mempool, all nodes should rebroadcast the corresponding template with their signatures (cf. issue #103) **It should be sufficient that B nodes (1) keep sending partially signed transactions to each other until they become fully signed (2) the leader keeps broadcasting fully signed transactions that are not in the memory pool**
- When a transaction has been found on chain B, nothing needs to be done **Only thing that can happen is that transfers are reverted from "seen in block" to "fully signed" in the case of re-orgs**
- When a transaction was found on chain B, but then got involved in a reorg, the node B needs to resync, then the corresponding template transaction needs to be rebuilt using up to date UTXOs, and look on chain and in the mempool for its status **Transactions no longer found on the chain after a re-org will be reverted to "fully signed". If this transaction is requested from the store normal validation may find that the UTXO's are no longer valid and the transaction will become "rejected". Perhaps rejected transactions should be be retried periodically by the current leader.**
- When a transaction has matured on chain B, nothing needs to be done
