### ISSUE TITLE
Resync transfers store upon coming back online

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/FederatedSidechains#137]
***In order to*** ensure that the cross chain transfer store is up to date after disconnecting / reconnecting
***As a*** federated member's B-node
***I want*** to trigger a re-validation of the transactions matching the cross chains transfers that were found on the chain A blocks that were created while I was offline

> NOTE:  
    - this resync process will also be used on reorg cf issue #135
    - a federation member cannot act as a leader or create template transactions until it has finished syncing and has a correct view of the UTXO available to release funds out of the multisig

#### Acceptance Criteria 

- As the node B re-syncs its chain, it saves informations about the multisig transactions that it notices on the B chain blocks
- Once the sync is finished, node B needs to ask node A for all the blocks past its last known block and recreate entries in its cross chain transfer store.
- It needs to then match the transactions in the mempool and on chain against these entries, and update their statuses. If a template / transaction is not found in either chain or mempool it needs to broadcast it with its own signature (or collect signatures if it is the leader).

**Comment by quantumagi** [comment]
Since the store records both the chain A and chain B tips it should be sufficient to ask for all blocks / deposits past its chain A tip.
