### ISSUE TITLE
Resync matured block deposits when a federated member's B-node comes back online

### ISSUE THREAD

**Issue by ferdeen** [stratisproject/FederatedSidechains#158]
***In order to*** ensure federated member's node-B matured block deposits (MBDs) are up to date after disconnecting / reconnecting.
***As a*** federated member's B-node.
***I want*** to trigger a re-sync of MBDs that were found on node-A that were created while I was offline.

> Note : node-A lives on chain A, and node-B lives on chain B.
[Diagram](https://github.com/stratisproject/FederatedSidechains/blob/master/assets/cross-chain-transfers/happy-path-1.svg)
        
      

#### Acceptance Criteria 

- When a node B re-sync is invoked, node A will start to create the missing MBDs.
- Once the MBDs are created, node A will send the blocks back to node B.

#### Example 

node-A MBDs 1 - 2 - 3 - 4 - 5 - 6
node-B MBDs 1 - 2 - 3 [**offline**]
node-B [comes online : **resyncs**]
node-A [**sends** Node-B] - 4 - 5 - 6

**Comment by bokobza** [comment]
Closed with https://github.com/stratisproject/FederatedSidechains/pull/160
