### ISSUE TITLE
Federation sidechain node reorg exception.

### ISSUE THREAD

**Issue by ferdeen** [stratisproject/FederatedSidechains#209]
Federation sidechain node 1 & 3 reorg exception. 
(In federation.ps1 script - agentprefix=fedside1 & fedside3).

During IBD.

Requires further investigation.

Logs attached.

[fedside1 reorg exception.txt](https://github.com/stratisproject/FederatedSidechains/files/2640514/fedside1.reorg.exception.txt)
[fedside3 reorg exception.txt](https://github.com/stratisproject/FederatedSidechains/files/2640515/fedside3.reorg.exception.txt)

**Comment by dangershony** [comment]
Code based has changed since this was created and there is no easy way to reproduce this, so waiting till we get this error again to have more info.

**Comment by monsieurleberre** [comment]
As discussed with @bep42, this issue is probably solved and is too complex to reproduce in an integration test to be worth the effort.
We will reopen it if we notice a problem as part of the testing effort using NaughtyNodes etc...
