### ISSUE TITLE
Mainchain federation nodes are not connecting to each other on local run

### ISSUE THREAD

**Issue by bokobza** [stratisproject/FederatedSidechains#250]
When running the federation using the ps1 scripts, the sidechains nodes all seem to connect to each other but the mainchain federation nodes don't connect to each other or outwards.
The mainchain user node connects outwards and receives blocks as expected.

**Comment by MithrilMan** [comment]
duplicate of https://github.com/stratisproject/StratisBitcoinFullNode/issues/2960
handling the issue there

**Comment by MithrilMan** [comment]
An easy way to ensure the mainchain keeps getting updated is changing the script, making use of -addnode to add a known testnet node to at least one gateway (better if multiple) this way the chain can keep being updated.
Alternatively, ensure to have a proper peers.json with valid testnet nodes

**Comment by bokobza** [comment]
Adding nodes using `-addnode` is the best solution.

**Comment by bokobza** [comment]
Closing this.
