### ISSUE TITLE
Missed POA slots show too many items

### ISSUE THREAD

**Issue by bokobza** [stratisproject/FederatedSidechains#258]
Every time a PoA member misses a slots, the console prints MISS.
This can grow to be very large if there are many misses.

Maybe we should reduce the # of items displayed.
![image](https://user-images.githubusercontent.com/1867877/49944284-fb2e1c80-fee1-11e8-910e-0a4946970fc8.png)

**Comment by noescape00** [comment]
Fixed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/2954

Fixes won't kick in before packages are upgraded
