### ISSUE TITLE
Amend dependency tree for sidechain Features.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/FederatedSidechains#273]
Consensus and Mining should be separated. Sidechain nodes don't need any of the Federation code but do need Consensus.

In the dependency tree as it is currently however, consensus is dependent on PoAFeature (needs SlotManager) which is in turn dependent on FederationGatewayFeature. As such all sidechain nodes will be much heavier than they need to be.

It also requires sidechain nodes to have configuration for `-sidechain -redeemscript ` , which I think is a pretty significant problem... we can discuss

**Comment by codingupastorm** [comment]
This is a pain, the features should be a bit nicer to work with like adding mining, consensus, and the federation but can see that the daemon is using a different setup so this isn't important for now

**Comment by MithrilMan** [comment]
something similar to what I needed in this PR:
https://github.com/stratisproject/FederatedSidechains/pull/260#issue-238421647
for the sidechain DNS seeder
