### ISSUE TITLE
NextMatureDepositHeight stops advancing

### ISSUE THREAD

**Issue by bokobza** [stratisproject/FederatedSidechains#293]
Running the federation, I see the following after a while:
![image](https://user-images.githubusercontent.com/1867877/50060269-c80db680-0189-11e9-94a2-018364d4b67e.png)

NOtice how the NextDepositHeight stopped advancing.

**Comment by bokobza** [comment]
Actually, it advances, but very slowly, and by 10,000 block increments.

**Comment by bokobza** [comment]
Same in the live network:
![image](https://user-images.githubusercontent.com/1867877/50060401-57679980-018b-11e9-874b-bf7eb02c3801.png)

**Comment by quantumagi** [comment]
The 10,000 figure can't be right:

`public const int MaxBlocksToCatchup = 1000;`

**Comment by quantumagi** [comment]
On the live network I see the store has suspended. That's expected while waiting for signatures, confirmed balances or for transactions to appear in the wallet.

**Comment by quantumagi** [comment]
See https://github.com/stratisproject/FederatedSidechains/pull/294.

The above PR will assist us in identifying any issues.

**Comment by quantumagi** [comment]
What I do notice now is that we are receiving the same blocks multiple times.

**Comment by quantumagi** [comment]
![image](https://user-images.githubusercontent.com/29645989/50075776-ec25d200-0233-11e9-808e-c824f8b72554.png)

**Comment by dangershony** [comment]
@quantumagi I don't understand do much what you are explaining.
Every time a chain advances it sends the new block to the other chain right?
However we need to also check blocks during IBD (sync up) and to avoid reorgs we only take the next block under max reorg 

So I would imagine that every time a block is found on any chain we push that block to the other chain for analysis, what I don't understand is what is the `MaxBlocksToCatchup` property.

**Comment by quantumagi** [comment]
@dev0tion , was that after PR #302?

**Comment by quantumagi** [comment]
@dangershony , the sidechain requests all blocks (starting at a specified height) from the mainchain when the sidechain receives a block from the mainchain that is ahead of the next expected block. The variable indicates the maximum number of blocks that the mainchain is allowed to return to the sidechain as a result of such a call.

**Comment by dev0tion** [comment]
@quantumagi this was before #302.
Pulled the latest now.

**Comment by bokobza** [comment]
I think this can be closed. When all the members are activated properly, everything works fine.
