### ISSUE TITLE
Question: Why Does Proof-of-Work Double-Validate State?

### ISSUE THREAD

**Issue by Mike-EEE** [stratisproject/FederatedSidechains#72]
I'm having a ball of a time meeting everyone in your [Discord channel](https://discordapp.com/channels/404643249798512652/461524150805331978). 😄 

However, something has arisen that I am trying to wrap my mind around, and it has to do with how Proof-of-Work is prioritized.  My interest here is possibly exploring how to modify how this is done in my own theoretical sidechain here through the amazingly impressive Stratis offering.

So it would seem, to start, that blocks are essentially a collection of transactions that have _already_ been _verified and validated_ by miners, and as having already been proven to be abiding by all the established rules of the protocol (no double-spending, etc).  My confusion lies in the subsequent POW aspect.  If every transaction within a block has _already_ been validated and verified, why does it need further validation in the form of solving this hashing riddle?

It would seem to me that the riddle is in the current "view" of available broadcasted transactions at the current time of assembling this next block, such as this: if given 100 valid transactions currently broadcasted and available to a miner, how many can be sorted into this next block in a way that not only maximizes the number of transactions removed from the outstanding queue/view but also yields the highest average value in both aggregate sum and related fees?

It seems to me that a scoring system could then be derived from questioning such as this, and that the first participating party who claims the highest score in this regard based on the currently available set of verified/valid broadcasted unspent transactions would win the block, and can therefore add it to the chain.  If several parties get the same configuration (or score) concurrently, then they split the reward evenly.

The other added benefit of POSt (sorry, it's not [POS](https://www.urbandictionary.com/define.php?term=POS) 😉) is that a vote could then be cast on that scored block/result based on the ownership of each staked participant, to verify and certify the result.  When the cumulative total of available voting parties with stake reaches over 50%, then the block is officially certified and added into the chain.

There must be something obvious here I am overlooking, so I am presenting it here to see if it's even possible to consider such a notion for a sidechain.  

Thank you again for your great work here.  Very inspiring and compelling potential!

**Comment by zeptin** [comment]
In a trustless system, you have no idea whether or not the miners have performed the validation in an honest fashion, so every user has to validate independently.

Additionally, validation of the transactions does not constitute part of the proof of work. The PoW hashing is needed in order to prevent malicious miners creating blocks with an alternate transaction history in them. There is a needed asymmetry between finding a usable nonce & validating that it does result in a block that is acceptable to the rest of the network.

**Comment by Mike-EEE** [comment]
Cool @zeptin thanks for that context.  That helps out a bit.  This is my first week of really diving into the guts here so please bear with me. 😆

I guess my first question is... are you saying that every user validates these blocks independently already?

As for malicious miners adding alternate transaction history, it would seem that what I am describing here would circumvent this.  If you could, I would really appreciate a walk through this with me to point out what I could be overlooking.

To resume my thinking here, if everyone ultimately verifies and validates each transaction in a block, that actually simplifies what I would be striving for here.

Essentially, what I am thinking is that let's say we have _x_ number of miners at any given time on the network, each with their own "view" of _y_-broadcasted UTXOs.  Every miner might have their own view of these broadcasted UTXOs (and they could differ considerably as some have received notifications of transactions that others have not), but each one could assemble according to their own algorithm to produce a "score" of some sort that would result in a _candidate block_ that they then in turn broadcast back out to the network to qualify for the next block.

From there, each staked member participating in this theoretical consensus process would verify each broadcasted candidate, starting with the highest score, working their way down looking for the first one that contains _100% valid transactions_ as established and defined by the network protocol.  

Each member then votes for their highest scoring candidate, the weight of which is determined by how much stake they have.  Once all parties have voted, the candidate with the greatest % is declared the winner.  Hopefully this result is over 50%, but if there are several candidates with similar but different scores, it could bifurcate into several valid candidates so that the winning result is less than 50%.  Even in this scenario, this is not a problem (I do not think) as each of these candidates represents _a 100% valid block_ to add as the next link in the chain as _verified_ by each voting member.

Thinking about this further, the process could then possibly take a step further reward all the members in the winning side of the vote with a bonus of some kind (to keep in line with the spirit of current mining).

That said, if a malicious party attempted to add a block that had invalid transactions, they would not succeed as those transactions would be verified as invalid and discounted as a legitimate candidate.

Again there might be something super obvious that I am missing here so I would certainly appreciate a pointer to the blind spot in my thinking here.

**Comment by Mike-EEE** [comment]
OK I have thought about this some more and I see the problem now:

Each node might have its own view, but the problem is coordinating the final result.  I have a few ideas on this, and will be presenting a proposal soon for further discussion.

Some thoughts in the meantime:

- BTC has been out for ten years now.  That is incredibly remarkable for a technology by any stretch.  Its intended goal was anonymous peer-to-peer payments.  This should be preserved, of course, with current market and network/technologies in mind.  This is sort of what I will be angling here in my proposal with a Stratis sidechain in mind as the primary context.
- I hope the value proposition here is clear: allowing Stratis sidechains over full control over how they operate is a _tremendous_ value and will for sure bring traction and brand value to Stratis and its offering here.

Closing this for now and will open a new issue as a proposal for what I am thinking here.

**Comment by Mike-EEE** [comment]
FWIW, this is very close to what I had/have in mind.  I would like to make it open source and not-so-gosh-darn-proprietary, of course. 😉 I am pretty sure a sidechain that features another spectrum of proof would show a lot of potential and promise for Stratis sidechains.

https://medium.com/hashgraph/i-want-your-vote-oh-wait-i-already-know-it-e1faa50b31ad
