### ISSUE TITLE
Rework the way transfer session

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/FederatedSidechains#75]
In the current implementation, sessions for transfering coins from chainA to chainB work this way:

For the block at height H on chainA 
- Read all deposits made to the multisig on chainA + corresponding OP_RETURNS
- If any, then derive from H a table ordering preferred leader for the given block
- If leader 1 is online, leader 1 generates a session containing all transaction deposit transaction number on block H + corresponding OP_RETURNS, then shares it with other federated node to warn them they should expect to sign a few transactions soon
- leader 1 creates a chain B transaction template for all transactions found on chain A's block H, propagates it to other fed members
- chainB members sign transaction template and return it until quorum
- leader 1 sends the signed transaction

Problems are
1 - sessions are not persisted so failure of leader node mid transfer is likely to result in an inconsistent state #76 
2 - picking up a sessions started by another node which went down is not tested well enough
3 - better naming in the code would improve readability

Solution
- use a database or a message queue to react to and persist session states
- monitor the target chain and match transaction to close the sessions
- sessions that are not closed can be monitored and picked up from the store / message queue

**Comment by monsieurleberre** [comment]
with @kogot we think that this could be a way to make this work:
N is the size of the federation.
- on block height H on chain A all A-nodes from the federation persist a list of transactions made to the multisig that should trigger deposits on the chain B
- the leader L is tied to the current height of chain A => when the chain A advances, the nodes will change the leader they agreed upon.
- when chain A reaches H + MaxReorg blocks, then the current leader L (leader for A-Height H+500) will generate a transaction template and propagate it until it gets enough signature to broadcast the transaction.
If during the interval from (H + MaxReorg) to (H + MaxReorg +1) the transaction has not been broadcasted (meaning that leader L failed to complete the signature process), then a new leader L' will emerge as a result of the height change in chain A.
- L' becomes the new leader for block H + MaxReorg + 1, he has the list of transactions that should appear in the mempool or in the chain B as a result of observing a multisig deposit on block H on chain A. 
If the transactions for block H have not yet been processed up to the point where they show in the mempool or on chain, then whatever happened with L will be ignored by other nodes (who should agree that new leader is L' based on chain A's height) then L' will be able to take care of it : L' has exactly the same info as L had when he was in charge of dealing with block H.
L' will deal with all unprocessed cross chain transfer sessions (it has a list of all its expectations) then will proceed with whatever new transactions can be found on block H+1.

etc..

It seems encouraging that this solution does not really need to rely on a distributed database, cache or messaging protocol between federation members.

Please let me know if that is not clear. If you need more info, or more importantly if you think we missed something to make this work.

A problem needs a bit more thinking: if chain A has bigger blocksizes than chain B, then it is possible that we cannot include all transactions from block H into one single block on chain B, and if that happens too often we will end up in a non viable situation...

**Comment by dangershony** [comment]
**After a discussion on the matter this is a proposal we came up with.**

N is the size of the federation.
- on block height H on chain A all A-nodes from the federation persist a list of transactions made to the multisig that should trigger deposits on the chain B
- the leader L is tied to the current height of chain A => when the chain A advances, the nodes will change the leader they agreed upon.
- when chain A reaches H + MaxReorg blocks, then the current leader L (leader for A-Height H+500) will generate a transaction template and propagate it until it gets enough signature to broadcast the transaction.
If during the interval from (H + MaxReorg) to (H + MaxReorg +1) the transaction has not been broadcasted (meaning that leader L failed to complete the signature process), then a new leader L' will emerge as a result of the height change in chain A.
- L' becomes the new leader for block H + MaxReorg + 1, he has the list of transactions that should appear in the mempool or in the chain B as a result of observing a multisig deposit on block H on chain A. 
If the transactions for block H have not yet been processed up to the point where they show in the mempool or on chain, then whatever happened with L will be ignored by other nodes (who should agree that new leader is L' based on chain A's height) then L' will be able to take care of it : L' has exactly the same info as L had when he was in charge of dealing with block H.
L' will deal with all unprocessed cross chain transfer sessions (it has a list of all its expectations) then will proceed with whatever new transactions can be found on block H+1.

etching..

It seems encouraging that this solution does not really need to rely on a distributed database, cache or messaging protocol between federation members.

Please let me know if that is not clear. If you need more info, or more importantly if you think we missed something to make this work.

A problem needs a bit more thinking: if chain A has bigger blocksizes than chain B, then it is possible that we cannot include all transactions from block H into one single block on chain B, and if that happens too often we will end up in a non viable situation...

**Comment by dangershony** [comment]
Sorry its not that clear yet the processes, can we try to describe it better? (perhaps a diagram)

One problem I see here is what if a leader misses his opportunity and the leadership passes to the next member, what are the next leader responsibilities? to processes previous block trx plus current block trx right?

If the second chance is missed then the next leader will processes (current-2) + (current-1) + n.

**Comment by kogot** [comment]
Yes, the idea was that new leader responsible for whatever previous L didn't finalise. Yes at some point we could have big tail of debt, but we believe it's going to be rare, more exceptional situation rather than normal state. And this debt will be covered soon.

**Comment by zeptin** [comment]
One potential issue is, it is not good for a federation member to sign any transaction more than once.
Say member X (doesn't have to be L) signs for transaction T during the (H + maxReorg) session, but then that session dies out (or we think it has died out).
Now L' orchestrates a new session as described in the proposal.
But where it says that the other members should ignore what happened during the previous session, I think this needs a bit of fleshing out.
If members have signed T there is a risk that the other nodes, whether inadvertently or through malice, could accumulate enough signatures
on the (H + maxReorg) session to broadcast T later. If a sufficient number of other members are busy constructing T' because they think
the session for T has failed, you can land up with two transfers on the sidechain instead of one. So you have to be very careful under which circumstances
you will allow a T' template to be made.
There are also timing considerations - not every node will be at precisely the same block height at any given instant, this makes it tricky
determining what previous session state to disregard, and who the leader should be at a given point, particularly if the window for orchestrating
a session is 1 block.

**Comment by dangershony** [comment]
>One potential issue is, it is not good for a federation member to sign any transaction more than once. Yes correct

>ut where it says that the other members should ignore what happened during the previous session, I think this needs a bit of fleshing out.  

No they should not ignore, the point is the template trx will be broadcast to all nodes so the leader will just continue from the current last template (and if need be ask peers for the signatures they already have of an existing template)

So yes crucial is that a peer/member does not sign an output more then once.

**Comment by dangershony** [comment]
Perhaps we can even put a condition place that a member must stop any work if they are not connected to at least 51% of members?


Additionally we can add notifications such as if a member goes down an email is sent to the current node operator.

**Comment by monsieurleberre** [comment]
Here is a suggestion from the meeting we had on Friday
https://github.com/stratisproject/FederatedSidechains/blob/master/Requirements/cross-chain-transfer.md

**Comment by monsieurleberre** [comment]
We think the design presented in https://github.com/stratisproject/FederatedSidechains/blob/master/Requirements/cross-chain-transfer.md is now final
